version: '3.7'

services:
  video-tapes:
    build: .
    volumes:
      - .:/app
    ports:
      - 5000:80
    depends_on:
      - db
  
  db:
    image: postgres
    environment:
      POSTGRES_DB: video_tapes
      POSTGRES_USER: aslakur
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432