version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: video_tapes
      POSTGRES_USER: aslakur
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
 

  rabbit:
    image: rabbitmq:3.6-management
    ports:
      - 15672:15672


  database_service:
    build:
      context: ./
      dockerfile: ./database_service/Dockerfile
    depends_on:
      - db
      - rabbit
    environment:
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"
        RABBIT_MANAGEMENT_PORT: "15672"


  
 