version: '3.7'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: video_tapes
      POSTGRES_USER: aslakur
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
 

  rabbit:
    image: rabbitmq:3.6-management
    ports:
      - 15672:15672
    logging:
      driver: none


  database_service:
    build:
      context: ./
      dockerfile: ./database_service/Dockerfile
    depends_on:
      - db
      - rabbit
    environment:
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"
        RABBIT_MANAGEMENT_PORT: "15672"
        SERVICE_STRING: "database_service.database_nameko_api"
        DB_CONFIG: "database_service/db-config.json"

  recommendation_service:
    build:
      context: ./
      dockerfile: ./recommendation_service/Dockerfile
    depends_on:
      - db
      - rabbit
    environment:
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"
        RABBIT_MANAGEMENT_PORT: "15672"
        SERVICE_STRING: "recommendation_service.recommendation_nameko_api"

  review_service:
    build:
      context: ./
      dockerfile: ./review_service/Dockerfile
    depends_on:
      - db
      - rabbit
    environment:
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"
        RABBIT_MANAGEMENT_PORT: "15672"
        SERVICE_STRING: "review_service.review_nameko_api"

  tape_service:
    build:
      context: ./
      dockerfile: ./tape_service/Dockerfile
    depends_on:
      - db
      - rabbit
    environment:
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"
        RABBIT_MANAGEMENT_PORT: "15672"
        SERVICE_STRING: "tape_service.tape_nameko_api"

  user_service:
    build:
      context: ./
      dockerfile: ./user_service/Dockerfile
    depends_on:
      - db
      - rabbit
    environment:
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbit"
        RABBIT_PORT: "5672"
        RABBIT_MANAGEMENT_PORT: "15672"
        SERVICE_STRING: "user_service.user_nameko_api"

  rest_api_service:
    build:
      context: ./
      dockerfile: ./rest_api_service/Dockerfile
    ports:
      - 5000:80
    depends_on:
      - db
      - rabbit

    environment:
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"
      RABBIT_MANAGEMENT_PORT: "15672"
  
    
    


  
 